package projects.bstOpticalNet.nodes.models;

/**
 * Enumerator indicating the rotation the node should perform over all
 * permutations with (ZigZig-ZigZag), (Left-Right), (BottomUp-TopDown)
 */
public enum Rotation {
    SEMI_ZIGZIGLEFT_BOTTOMUP,
    SEMI_ZIGZIGRIGHT_BOTTOMUP,
    SEMI_ZIGZAGLEFT_BOTTOMUP,
    SEMI_ZIGZAGRIGHT_BOTTOMUP,
    SEMI_ZIGZIGLEFT_TOPDOWN,
    SEMI_ZIGZAGLEFT_TOPDOWN,
    SEMI_ZIGZIGRIGHT_TOPDOWN,
    SEMI_ZIGZAGRIGHT_TOPDOWN,
    ZIG_BOTTOMUP,
    ZIGZIGLEFT_BOTTOMUP,
    ZIGZIGRIGHT_BOTTOMUP,
    ZIGZAGLEFT_BOTTOMUP,
    ZIGZAGRIGHT_BOTTOMUP,
    ZIGZIGLEFT_TOPDOWN,
    ZIGZAGLEFT_TOPDOWN,
    ZIGZIGRIGHT_TOPDOWN,
    ZIGZAGRIGHT_TOPDOWN,
    NULL
}
